### ISSUE TITLE
Losing ability to use mouse

### ISSUE THREAD

**Issue by Titaniumtown** [galister/wlx-overlay-s#10]
First off, amazing project! But I did want to point out an issue I'm experiencing. Randomly I lose the ability to use a controller as a mouse on the projected display. This seems to happen after I finish using other VR applications (games) and then closing them out, but I haven't found a good way to reproduce the issue.

I'm using a quest 2 via ALVR and steamVR on nobara linux, KDE (wayland).

**Comment by SpookySkeletons** [comment]
Reporting monado is affected by Wayland mouse becoming stuck, entire desktop is unresponsive to mouse until wlx is stopped.

**Comment by galister** [comment]
i got confirmation that this got fixed, if you encounter it again please open a new issue

**Comment by Kirottu** [comment]
This seems to be affecting me these days, sometimes it spuriously resolves but I haven't figured out a good way to reproduce it.

Using WiVRn on niri, with latest release of wlx-overlay-s as of writing this.

**Comment by galister** [comment]
Is it really the mouse, not the pipewire stream stopping? I had instances where if the screen would go to sleep, the pipewire stream stops and doesn't recover.

**Comment by Kirottu** [comment]
The stream was very much responsive (keyboard shortcuts work just fine, cursor does move), and my actual mouse didn't work either when that happened. Running wev, the app received mouse events at all until I managed to press something or it resolved itself.

**Comment by galister** [comment]
So it's just the clicks that don't work, the movement does? Most of the time I get that, it's a stuck modifier.

**Comment by Kirottu** [comment]
Oh, I somehow managed to completely typo that. I meant to say that wev received no mouse events at all.
