### ISSUE TITLE
Performance implications of high resolution displays

### ISSUE THREAD

**Issue by Titaniumtown** [galister/wlx-overlay-s#11]
I am experiencing extreme performance degradation when trying to display both of my 1440p displays in VR. I haven't dug into the code of the project extensively yet but my gut feeling is that maybe the resolution being displayed is too high and that the actual resolution of the display in VR should be adjusted based off of the headset resolution and the distance to the display in virtual space.

**Comment by galister** [comment]
Hi, what desktop are you on? Most importantly, X or Wayland?

**Comment by Titaniumtown** [comment]
wayland, kde

**Comment by Titaniumtown** [comment]
@galister I will test when I'm at home, I never used the original WlxOverlay, but I'll figure that out. I'll report back with results.

**Comment by galister** [comment]
@Titaniumtown please try with the latest commit 5bbaf59

**Comment by galister** [comment]
much of the capture logic has been reworked, so i'll be closing this if there's no response by weekend

**Comment by Titaniumtown** [comment]
It works fine now. Sorry for the tardy response.
