### ISSUE TITLE
Crate won't compile due to missing libraries on system.

### ISSUE THREAD

**Issue by 2-3-5-41** [galister/wlx-overlay-s#13]
# Problem

After cloning the repo and using the `cargo run --release` command, I- and I'm sure others- have been met with a panic message, and/or compiler errors due to several missing libraries not found on their system.

---

What are all the locally installable dependencies to allow for this crate to build? and maybe they should be listed in the `README.md` to be installed *before* trying to build/run the crate.

**Comment by galister** [comment]
done, see readme
