### ISSUE TITLE
[question] how do I make it start with steamvr on linux?

### ISSUE THREAD

**Issue by OzzyHelix** [galister/wlx-overlay-s#18]
I have a problem where its not starting with steamvr/alvr and I would like to know how to start it with steamvr
any help with this would be appreciated thanks Ozzy

**Comment by galister** [comment]
hi, what version is this? appimage or local build?

**Comment by galister** [comment]
normally it'll start with steamvr after you start it once from the terminal (and select your screens)

**Comment by OzzyHelix** [comment]
I'm using the AUR package and for some reason I need to manually start it to get it running in SteamVR

**Comment by OzzyHelix** [comment]
it shows up in the overlay options but doesn't start with SteamVR 2.4.4
![image](https://github.com/galister/wlx-overlay-s/assets/29835364/316eadc2-588f-46e4-a4aa-f4ef635fe224)

**Comment by OzzyHelix** [comment]
its not launching with SteamVR to get it working I need to connect my headset with ALVR then go into pass though on my quest 3 walk to my monitor and launch Wlx-Overlay-S manually

**Comment by galister** [comment]
you can always just start it from the alvr on-connect script:
```bash
/path/to/wlx-overlay-s &
```

**Comment by OzzyHelix** [comment]
in my case the binary is at `/usr/bin/wlx-overlay-s` and when you say on connect do you mean the audio setup script?

**Comment by galister** [comment]
yes, or whatever you have set as the on-connect script under the ALVR settings tab.

I just tried SteamVR 2.4.4 and it does not auto-start for me either. It does however work again on SteamVR 2.5.1 (beta), so I'll write this off as a SteamVR bug.

**Comment by OzzyHelix** [comment]
I've been advised not to use the steamvr beta by the people in the alvr discord so its why I am staying on stable tho I could try it

**Comment by galister** [comment]
I don't recommend it either. However, the fact that it works on the 1.27 branch and beta branch makes me think there is a SteamVR bug in 2.4.4 that prevents it from starting.

So I guess I'll close this for now and add it as a known issue. Thanks for reporting.
