### ISSUE TITLE
failed to determine active runtime file path for this environment

### ISSUE THREAD

**Issue by donalffons** [galister/wlx-overlay-s#19]
Thank you for this project. I would love to give it a try with my System (Manjaro Linux, nVidia GPU, Oculus Quest 3).

I've just installed the program from AUR and trying to run it, I get the following error:
```
$ wlx-overlay-s
INFO [wlx_overlay_s] Welcome to wlx-overlay-s version 0.3.2!
Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to determine active runtime file path for this environment
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime()
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties
WARN [wlx_overlay_s::backend::openxr] Will not use OpenXR: Failed to enumerate OpenXR extensions.
Unable to read VR Path Registry from /home/sebastian/.config/openvr/openvrpaths.vrpath
WARN [wlx_overlay_s::backend::openvr] Will not use OpenVR: Context init failed
ERROR [wlx_overlay_s] No more backends to try
```

Any suggestions on how I can get starting to fix that? What is likely to cause this?

**Comment by Scrumplex** [comment]
You could check if `/home/sebastian/.config/openvr/openvrpaths.vrpath` is a proper file (or if its target exists it's a symlink) and send the contents of the file here if it exists

**Comment by donalffons** [comment]
Thanks for the quick reply! That file doesn't exist. I'll research why its missing and how to create it....

**Comment by Scrumplex** [comment]
That file is usually generated by SteamVR. I assume you weren't planning on using SteamVR?

**Comment by donalffons** [comment]
After installing SteamVR through Steam, this is what I get

```
$ wlx-overlay-s
INFO [wlx_overlay_s] Welcome to wlx-overlay-s version 0.3.2!
Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to determine active runtime file path for this environment
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to load a runtime
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime()
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties
WARN [wlx_overlay_s::backend::openxr] Will not use OpenXR: Failed to enumerate OpenXR extensions.
VR Server (v1710958318)

Using breakpad crash handler
Setting breakpad minidump AppID = 250820
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
03/27 09:41:26 Init: Installing breakpad exception handler for appid(250820)/version(2.4.4)/tid(427773)
WARN [wlx_overlay_s::backend::openvr] Will not use OpenVR: Context init failed
ERROR [wlx_overlay_s] No more backends to try
```

The contents of my `openvrpaths.vrpath` are:
```
{
	"config" : 
	[
		"/home/sebastian/.local/share/Steam/config"
	],
	"external_drivers" : null,
	"jsonid" : "vrpathreg",
	"log" : 
	[
		"/home/sebastian/.local/share/Steam/logs"
	],
	"runtime" : 
	[
		"/home/sebastian/.local/share/Steam/steamapps/common/SteamVR"
	],
	"version" : 1
}
```

**Comment by Scrumplex** [comment]
If you want to use an OpenXR runtime like Monado or WiVRn, you probably need to set it as your active runtime first. 

The line `Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to determine active runtime file path for this environment` indicates that none was found. You would usually symlink a file to `~/.config/openxr/1/active_runtime.json` to set an active runtime. Alternatively, you could run `wlx-overlay-s` with the environment variable `XR_RUNTIME_JSON` that points to the manifest file of Monado/WiVRn

**Comment by galister** [comment]
@donalffons the last piece of logs you sent show that you didn't have SteamVR running properly when you started the overlay.

If you plan on using SteamVR (with ALVR) then first open ALVR and start SteamVR using the `Launch SteamVR` button. Once you have a green SteamVR status window with no errors, then start `wlx-overlay-s`.
The overlay will auto-start next time.

If you want to use OpenXR, try Envision. It's a helper app that sets up OpenXR for you. For the Quest, you want to pick the WiVRn profile. The overlay doesn't auto-start on OpenXR, so you'll want to start it each time.
https://gitlab.com/gabmus/envision

In case you need more help, feel free to reach out on our community chat:
- Discord: https://discord.gg/gHwJ2vwSWV
- Matrix Space: #linux-vr-adventures:matrix.org

**Comment by donalffons** [comment]
I've managed to get ALVR running and connected to my headset (It say `streaming`). Running `wlx-overlay-s` then seems to work fine (no errors). Inside the headset, I'm then in a black void with just a blue circle on the floor below me...

However, some other things like the "Steam V Tutorial" doesn't seem to run, so I believe I'm now having more of a Steam / ALVR issue, than a wlx-overlay-s issue. I'm therefore closing this now.

Thanks a lot for your help!
