### ISSUE TITLE
[feature request] clock telling you how long you are in vr

### ISSUE THREAD

**Issue by OzzyHelix** [galister/wlx-overlay-s#41]
xsoverlay has a clock showing the amount of time you have been in steamvr it would be cool if that was a feature on this thanks ozzy

**Comment by stuin** [comment]
I added one a while ago that tells you how long wlx-overlay has been running, you can simply replace alt clock 1 in the watch.yaml config file with this.

```
# uptime
  - type: Label
    rect: [210, 90, 200, 50]
    font_size: 24
    fg_color: "#99BBAA"
    source: Timer
    format: "%H:%M" # 23:59
  - type: Label
    rect: [210, 60, 200, 50]
    font_size: 14
    fg_color: "#99BBAA"
    source: Static
    text: "Uptime"
```

**Comment by OzzyHelix** [comment]
where would I find the watch.yaml file?

**Comment by galister** [comment]
hi, see the wiki [here](https://github.com/galister/wlx-overlay-s/wiki/Customize-UI#customize-watch).

**Comment by OzzyHelix** [comment]
I didn't know you could customize it like this I just assumed it was something I would have to ask for as a feature

**Comment by OzzyHelix** [comment]
this is what worked for me I just moved the Japan time to Alt clock 2 thanks guys sorry I assumed this wasn't a feature yet also having the seconds is the change I made thanks tho closing 
```
# uptime
  - type: Label
    rect: [210, 90, 200, 50]
    font_size: 14
    fg_color: "#99BBAA"
    source: Timer
    format: "%H:%M:%S" # 23:59
  - type: Label
    rect: [210, 60, 200, 50]
    font_size: 14
    fg_color: "#99BBAA"
    source: Static
    text: "Uptime"
```
