### ISSUE TITLE
Rounded Corners

### ISSUE THREAD

**Issue by AdalynBlack** [galister/wlx-overlay-s#55]
Hi, so I was looking at the code and documentation and discovered that there's a whole host of configuration files that can be tweaked to change the color, size, position, and contents of all the different buttons created by wlx-overlay-s
However
I noticed very quickly that there was a lack of options to add in rounded corners to panels, labels, buttons, etc
sooo
I ended up spending a bit too long implementing it myself (I'm not sure if the missing key labels is because I forgot something in the setup or because I messed up the keyboard implementation):
![image](https://github.com/user-attachments/assets/bb3d5e92-c784-4998-961f-1c191421be50)

The current implementation is fairly unoptimal, as it calculates the shape of each corner in the box every time a new rectangle is drawn, but once I have it optimized and well integrated with the existing code, would this be a change that would make sense in wlx-overlay-s?

**Comment by galister** [comment]
Looks great! Those rounded corners really make a huge difference.

Normally, the background layer (render_bg) is only ever rendered once for each UI window, then it stays in GPU memory for the rest of the UI window's lifetime. So calculating the corners is not a huge issue there.

The highlight layer (render_hl) is done on each frame, but there will be quite few draw calls required, as it is only done mouse hover and activated buttons, etc.

Want to push your code in a draft PR, at least?

**Comment by AdalynBlack** [comment]
Sure!
I'll put in a draft PR

**Comment by AdalynBlack** [comment]
Resolved in #56
