### ISSUE TITLE
wlx-overlay-s doesn't show anything inside VR and logs a segfault in libvulkan_radeon.so in dmesg

### ISSUE THREAD

**Issue by RiQuY** [galister/wlx-overlay-s#6]
Description
---
wlx-overlay-s doesn't show anything on the wrist. When checking dmesg I found the following segfault.

wlx-overlay-s was compiled and executed using the latest commit on main ([8116864](https://github.com/galister/wlx-overlay-s/tree/81168644166c270e43ae559b18799fd36375216b)), from this repo (https://github.com/SpookySkeletons/xr-overlays) with index_camera_passthrough disabled.

The runtime used was Monado + Envision in this commit https://gitlab.com/gabmus/envision/-/pipelines/1172008838

`dmesg -T `
```
[dom 11 feb 05:34:02 2024] usb 2-5.1: Found UVC 1.00 device 3D Camera (28de:2400)
[dom 11 feb 05:34:02 2024] input: 3D Camera: eTronVideo as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb2/2-5/2-5.1/2-5.1:1.0/input/input28
[dom 11 feb 05:39:58 2024] input: WlxOverlay-S Keyboard-Mouse Hybrid Thing as /devices/virtual/input/input29
[dom 11 feb 05:39:58 2024] show_signal_msg: 53 callbacks suppressed
[dom 11 feb 05:39:58 2024] wlx-overlay-s[27638]: segfault at 10 ip 00007f13cf5cc7ca sp 00007ffc1c151660 error 4 in libvulkan_radeon.so[7f13cf48d000+458000] likely on CPU 5 (core 5, socket 0)
[dom 11 feb 05:39:58 2024] Code: e4 55 89 f5 53 48 81 ec 68 08 00 00 48 89 8c 24 98 00 00 00 b9 40 00 00 00 64 48 8b 04 25 28 00 00 00 48 89 84 24 58 08 00 00 <48> 8b 47 10 48 8d bc 24 50 06 00 00 48 89 bc 24 88 00 00 00 48 89
[dom 11 feb 05:53:26 2024] hrtimer: interrupt took 20489 ns
[dom 11 feb 06:04:21 2024] perf: interrupt took too long (3156 > 3132), lowering kernel.perf_event_max_sample_rate to 63300
```

System info
---
My HMD is a Valve Index + Controllers and basestations 2.0

System info from `inxi -GSC -xx` command:
<details>
  <summary>click to collapse</summary>
<pre>
<code>
System:
  Host: localhost.localdomain Kernel: 6.7.4-1-default arch: x86_64 bits: 64
    compiler: gcc v: 13.2.1
  Desktop: KDE Plasma v: 5.27.10 tk: Qt v: 5.15.12 wm: kwin_wayland dm:
    1: GDM 2: SDDM note: stopped Distro: openSUSE Tumbleweed 20240209
CPU:
  Info: 8-core model: AMD Ryzen 7 1700X bits: 64 type: MT MCP arch: Zen rev: 1
    cache: L1: 768 KiB L2: 4 MiB L3: 16 MiB
  Speed (MHz): avg: 3122 high: 3493 min/max: 2200/3400 boost: enabled cores:
    1: 3400 2: 3061 3: 2826 4: 2796 5: 3218 6: 2931 7: 3120 8: 3476 9: 2795
    10: 2811 11: 3400 12: 2843 13: 3493 14: 3450 15: 3098 16: 3242
    bogomips: 108628
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: Blackmagic Design Intensity Pro 4K driver: N/A pcie:
    speed: 2.5 GT/s lanes: 4 bus-ID: 04:00.0 chip-ID: bdbd:a139
  Device-2: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
    vendor: XFX Pine driver: amdgpu v: kernel arch: RDNA-1 pcie: speed: 16 GT/s
    lanes: 16 ports: active: DP-1,HDMI-A-1 off: DP-2 empty: DP-3
    bus-ID: 0a:00.0 chip-ID: 1002:731f
  Device-3: Valve 3D Camera driver: uvcvideo type: USB rev: 3.2
    speed: 5 Gb/s lanes: 1 bus-ID: 2-5.1:4 chip-ID: 28de:2400
  Device-4: Logitech StreamCam
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo type: USB rev: 3.2
    speed: 5 Gb/s lanes: 1 bus-ID: 6-1.2:4 chip-ID: 046d:0893
  Display: wayland server: X.org v: 1.21.1.11 with: Xwayland v: 23.2.4
    compositor: kwin_wayland driver: X: loaded: modesetting unloaded: fbdev,vesa
    dri: radeonsi gpu: amdgpu display-ID: :1 screens: 1
  Screen-1: 0 s-res: 4480x1440 s-dpi: 96
  Monitor-1: DP-1 pos: primary,top-left res: 2560x1440 dpi: 108
    diag: 690mm (27.15")
  Monitor-2: HDMI-A-1 pos: bottom-r res: 1920x1080 dpi: 96
    diag: 587mm (23.1")
  API: EGL v: 1.5 platforms: device: 0 drv: radeonsi device: 1 drv: swrast
    surfaceless: drv: radeonsi wayland: drv: radeonsi x11: drv: radeonsi
    inactive: gbm
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.5 glx-v: 1.4
    direct-render: yes renderer: AMD Radeon RX 5700 XT (radeonsi navi10 LLVM
    17.0.6 DRM 3.57 6.7.4-1-default) device-ID: 1002:731f
  API: Vulkan v: 1.3.275 surfaces: xcb,xlib,wayland device: 0
    type: discrete-gpu driver: N/A device-ID: 1002:731f
</code>
</pre>
</details>

Addional logs
---

Logs from terminal:
- https://gist.github.com/RiQuY/c1cbfb046d1db9ac25cd46dec6dc6882

Output from `coredumpctl gdb /media/Almacen/Programas/xr-overlays/wlx-overlay-s/target/release/wlx-overlay-s`:
-  https://gist.github.com/RiQuY/5257a820d21bf1089fa1069d571ee5f1

The coredump was gathered with debuginfod disabled because the openSUSE was having problems downloading the debuginfod, if it is necesary I can run the command again to check if now it is able to download debuginfod.

**Comment by Scrumplex** [comment]
Relevant upstream issue: https://github.com/vulkano-rs/vulkano/issues/2465
