### ISSUE TITLE
Feat: IPD preview text

### ISSUE THREAD

**Issue by PassiveLemon** [galister/wlx-overlay-s#62]
The IPD label doesn't have a value when using uidev, would be nice for there to be one:

```
- type: Label
    rect: [258, 30, 200, 50]
    font_size: 24
    fg_color: "#93cb6b"
    source: Ipd
````
![image](https://github.com/user-attachments/assets/655afd1e-98d4-42ba-a403-5fd04a6859f4)

Sidenote: Is text usually supposed to have some artifacting? You can kind of see it between the B and the D in Kbd

**Comment by galister** [comment]
Try to increase the canvas resolution (top of yaml) as well as the text sizes, see if that gets rid of the artifacting.

**Comment by galister** [comment]
https://github.com/galister/wlx-overlay-s/commit/939a537d208854a383a2a1e74496de90b00ee6cc

**Comment by PassiveLemon** [comment]
> Try to increase the canvas resolution (top of yaml) as well as the text sizes, see if that gets rid of the artifacting.

Yeah, changing font size helps, bigger having less artifacts. I want the watch to be small though it's a bit of a challenge.

**Comment by galister** [comment]
could be an issue with the font shader
