### ISSUE TITLE
Document corner radius

### ISSUE THREAD

**Issue by PassiveLemon** [galister/wlx-overlay-s#66]
Upon trying to use the uidev for my 0.4.2 panel configurations, it returns `Error: elements: missing field `corner_radius` at line 7 column 3`.

The new corner radius is not documented in the Wiki or mentioned in the release notes for 0.4.3, it can only be found in the configs in `src/res/`

**Comment by galister** [comment]
instead we need to make it optional

**Comment by galister** [comment]
it is now optimal, and i also added it to the wiki
