### ISSUE TITLE
Clipboard stops working when starting wlx-overlay-s on KDE Plasma 6.1

### ISSUE THREAD

**Issue by OzzyHelix** [galister/wlx-overlay-s#74]
I have been having trouble with wlx-overlay-s where when I start it my clipboard stops working I can paste sometimes within apps but not between apps and the problem remains until I logout and log back in any ideas why it would do that

Ozzy

**Comment by galister** [comment]
Wlx doesn't touch your clipboard in any way.

I think what you're encountering is that the windows you're trying to paste into are not native Wayland windows, but X11 windows running under XWayland. Some desktop envs (like KDE) refuse to sync the clipboard with such windows, as X11 is considered a less secure platform.

Might want to try using a 3rd party tool, if clipboard sync is important to you. One such tool that we know to be working is this: https://github.com/dnut/clipboard-sync
