### ISSUE TITLE
Caps lock key is missing

### ISSUE THREAD

**Issue by Mhowser** [galister/wlx-overlay-s#77]
I have had a moment were I bumped my physical caps lock key and could not toggle it with the virtual keyboard overlay.
![Screenshot_20240908_050542](https://github.com/user-attachments/assets/b7e11af1-fdd9-46d0-a0b6-16290a26c76d)
It looks like there are 2 `menu` keys, the left one should be replaced with the caps lock.

**Comment by galister** [comment]
hi, thanks for trying the tool!

i'm happy to say that the keyboard is fully customizable!

1. grab an up-to-date keyboard template:
```bash
wget -O ~/.config/wlxoverlay/keyboard.yaml https://github.com/galister/wlx-overlay-s/raw/main/src/res/keyboard.yaml
```

2. edit the file; in the `main_layout` section, replace `"XF86Favorites"` with `"Caps"`

let me know if this works for you.

**Comment by Mhowser** [comment]
This has solved the problem. Thanks for the help!
