### ISSUE TITLE
Issues using desktop on any Wayland DE

### ISSUE THREAD

**Issue by RockyTheProtogen** [galister/wlx-overlay-s#88]
I am experiencing issues trying to use the desktop view on Wayland DEs. If I open the display, it is blank (you can't see it's there) and hovering or clicking it will sometimes crash SteamVR with a -203. It also has a chance of crashing the game with SteamVR. I will provide a log next time this happens.

If it helps, I am using an Intel i5 10th gen with a Nvidia RTX 3060 Lite Hash Rate. And yes, it works (almost) flawlessly on Xorg.

Anyway, what diagnostic info do I need to share?

**Comment by galister** [comment]
Check the logs at `/tmp/wlx.log`, there's a line "If screens are blank for you [...]", follow that.

**Comment by RockyTheProtogen** [comment]
Here are some logs:
[wlx.log](https://github.com/user-attachments/files/17482393/wlx.log)
[vrcompositor-linux.txt](https://github.com/user-attachments/files/17482410/vrcompositor-linux.txt)
[vrstartup-linux.txt](https://github.com/user-attachments/files/17482429/vrstartup-linux.txt)
[webhelper_vr.txt](https://github.com/user-attachments/files/17482431/webhelper_vr.txt)

**Comment by galister** [comment]
i meant to follow this part:

```
WARN [wlx_overlay_s::overlays::screen] Using DMA-buf capture. If screens are blank for you, switch to SHM using:
WARN [wlx_overlay_s::overlays::screen] echo 'capture_method: pw_fallback' > ~/.config/wlxoverlay/conf.d/pw_fallback.yaml
```

**Comment by RockyTheProtogen** [comment]
> echo 'capture_method: pw_fallback' > ~/.config/wlxoverlay/conf.d/pw_fallback.yaml

I'll give it a shot, didn't catch that at first, sorry.

**Comment by RockyTheProtogen** [comment]
Okay, so it does work. I've been looking for a solution for a while, didn't even know there was a log for it.. Thanks for telling me this.

Also, as a side note, the overlay has been the nicest one I've used yet. Good job.

**Comment by galister** [comment]
this fallback method is slower than DMA-buf, but seeing that you have a single 1080p display, it's likely not going to be an issue.

as to why it doesn't work with DMA-buf; nvidia is known to have issues from time to time, so it might be worth trying with different driver versions.

**Comment by RockyTheProtogen** [comment]
> this fallback method is slower than DMA-buf, but seeing that you have a single 1080p display, it's likely not going to be an issue.
> 
> as to why it doesn't work with DMA-buf; nvidia is known to have issues from time to time, so it might be worth trying with different driver versions.

Well, slow shouldn't matter too much anyway since all I do is control Spotify and do average tasks. 

Average Nvida, doesn't matter what platform it is on, it will always cause problems. 

Anyway, I'll leave the issue here. Have a good day, galister.
